language: clojure
lein: lein2
sudo: true

before_install: yes | sudo lein upgrade
install:
  - (cd cloverage && lein2 deps)
  - (cd lein-cloverage && lein2 deps)

before_script:
  - npm install -g eclint
  - eclint check .* **
  - (cd cloverage && lein2 cljfmt check)
  - (cd lein-cloverage && lein2 cljfmt check)
script:
  - (cd cloverage && lein2 test)
  - (cd lein-cloverage && lein2 test)

cache:
  directories:
    - $HOME/.m2

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

after_success:
  - bash deploy.sh
